import type { PixelMap } from "../pixelmap.js";

// A coiled serpent biting its own tail — a ring (annulus, generated
// analytically rather than hand-drawn — see the M6 CHANGELOG entry for the
// generation approach) with alternating deep-plum/amethyst scale bands and a
// jaw/eye picked out near one point of the ring where the head overlaps the
// tail. 48x48 per the spec (larger than every other monster). idle1 is the
// ring one pixel narrower with the scale bands phase-shifted, a slow
// "breathing coil" rather than a walk cycle.
export const ouroborosIdle0: PixelMap = {
	name: "ouroboros_idle0",
	width: 48,
	height: 48,
	legend: {
		O: 0, // ink brown — outline
		P: 32, // deep plum — dark scale band
		p: 33, // bright amethyst — light scale band
		j: 27, // cream — jaw/fangs
		e: 34, // ember red — eye
	},
	rows: [
		"................................................",
		"................................................",
		"................................................",
		"..................OOOOOOOOOOOO..................",
		"...............OOOPPPPPPppppppOOO...............",
		".............OOpppPPPPPPppppppPPPOO.............",
		"............OpppppPPPPPPppppppPPPPPO............",
		"..........OOpppppppPPPPPpppppPPPPPPPOO..........",
		".........OPPPppppppPPPPPpppppPPPPPPpppO.........",
		"........OPPPPppppppPPPPPpppppPPPPPPppppO........",
		".......OPPPPPPppppppPPPPppppPPPPPPppppppO.......",
		".......OPPPPPPPpppppPPPPppppPPPPPpppppppO.......",
		"......OpPPPPPPPPpppOOOOOOOOOOPPPppppppppPO......",
		".....OppppPPPPPPppO..........OPPppppppPPPPO.....",
		".....OpppppPPPPPOO............OOpppppPPPPPO.....",
		"....OpppppppPPPO................OpppPPPPPPPO....",
		"....OpppppppppO..................OPPPPPPPPPO....",
		"....OpppppppppO..................OPPPPPPPPPO....",
		"...OPPPppppppO....................OPPPPPPpppO...",
		"...OPPPPPPppO......................OPPppppppO...",
		"...OPPPPPPPPO......................OppppppppO...",
		"...OPPPPPPPPO......................OppppppppO...",
		"...OPPPPPPPPO......................OpppppjjjO...",
		"...OPPPPPPPPO......................OpppppjjjO...",
		"...OppppppppO......................OPPPPPjjjO...",
		"...OppppppppO......................OPPPPPjjjO...",
		"...OppppppppO......................OPPPPPPPPO...",
		"...OppppppppO......................OPPPPPPPPO...",
		"...OppppppPPO......................OppPPPPPPO...",
		"...OpppPPPPPPO....................OppppppPPPO...",
		"....OPPPPPPPPPO..................OpppppppppO....",
		"....OPPPPPPPPPO..................OpppppppppO....",
		"....OPPPPPPPpppO................OPPPpppppppO....",
		".....OPPPPPpppppOO............OOPPPPPpppppO.....",
		".....OPPPPppppppPPO..........OppPPPPPPppppO.....",
		"......OPppppppppPPPOOOOOOOOOOpppPPPPPPPPpO......",
		".......OpppppppPPPPPppppPPPPpppppPPPPPPPO.......",
		".......OppppppPPPPPPppppPPPPppppppPPPPPPO.......",
		"........OppppPPPPPPpppppPPPPPppppppPPPPO........",
		".........OpppPPPPPPpppppPPPPPppppppPPPO.........",
		"..........OOPPPPPPPpppppPPPPPpppppppOO..........",
		"............OPPPPPppppppPPPPPPpppppO............",
		".............OOPPPppppppPPPPPPpppOO.............",
		"...............OOOppppppPPPPPPOOO...............",
		"..................OOOOOOOOOOOO..................",
		"................................................",
		"................................................",
		"................................................",
	],
};

export const ouroborosIdle1: PixelMap = {
	name: "ouroboros_idle1",
	width: 48,
	height: 48,
	legend: {
		O: 0,
		P: 32,
		p: 33,
		j: 27,
		e: 34,
	},
	rows: [
		"................................................",
		"................................................",
		"................................................",
		"................................................",
		"..................OOOOOOOOOOOO..................",
		"...............OOOppppppPPPPPPOOO...............",
		".............OOPPPppppppPPPPPPpppOO.............",
		"............OPPPPPPpppppPPPPPppppppO............",
		"...........OpPPPPPPpppppPPPPPppppppPO...........",
		"..........OppPPPPPPpppppPPPPPppppppPPO..........",
		".........OppppPPPPPPppppPPPPppppppPPPPO.........",
		"........OppppppPPPPPppppPPPPpppppPPPPPPO........",
		".......OppppppppPPPOOOOOOOOOOpppPPPPPPPPO.......",
		"......OPPPppppppPPO..........OppPPPPPPpppO......",
		"......OPPPPpppppOO............OOPPPPPppppO......",
		".....OPPPPPPpppO................OPPPppppppO.....",
		".....OPPPPPPPPO..................OppppppppO.....",
		".....OPPPPPPPPO..................OppppppppO.....",
		"....OppPPPPPPO....................OppppppPPO....",
		"....OpppppPPO......................OppPPPPPO....",
		"....OpppppppO......................OPPPPPPPO....",
		"....OpppppppO......................OPPPPPPPO....",
		"....OpppppppO......................OPPPPjjjO....",
		"....OpppppppO......................OPPPPjjjO....",
		"....OPPPPPPPO......................OppppjjjO....",
		"....OPPPPPPPO......................OppppjjjO....",
		"....OPPPPPPPO......................OpppppppO....",
		"....OPPPPPPPO......................OpppppppO....",
		"....OPPPPPppO......................OPPpppppO....",
		"....OPPppppppO....................OPPPPPPppO....",
		".....OppppppppO..................OPPPPPPPPO.....",
		".....OppppppppO..................OPPPPPPPPO.....",
		".....OppppppPPPO................OpppPPPPPPO.....",
		"......OppppPPPPPOO............OOpppppPPPPO......",
		"......OpppPPPPPPppO..........OPPppppppPPPO......",
		".......OPPPPPPPPpppOOOOOOOOOOPPPppppppppO.......",
		"........OPPPPPPpppppPPPPppppPPPPPppppppO........",
		".........OPPPPppppppPPPPppppPPPPPPppppO.........",
		"..........OPPppppppPPPPPpppppPPPPPPppO..........",
		"...........OPppppppPPPPPpppppPPPPPPpO...........",
		"............OppppppPPPPPpppppPPPPPPO............",
		".............OOpppPPPPPPppppppPPPOO.............",
		"...............OOOPPPPPPppppppOOO...............",
		"..................OOOOOOOOOOOO..................",
		"................................................",
		"................................................",
		"................................................",
		"................................................",
	],
};
